name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}

  ui_tests:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright and browsers
        run: npx playwright install --with-deps

      - name: Wait for Render app to be live
        run: |
          echo "Waiting for Render app to be available..."
          until curl -s --head --request GET https://myapp.onrender.com | grep "200 OK"; do
            echo "Still waiting..."
            sleep 5
          done
          echo "App is live."

      - name: Run Playwright tests against Render
        env:
          BASE_URL: https://myapp.onrender.com
        run: npx playwright test

  unit_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test
